"""Add User blocking fields and Penalty model

Revision ID: 90e64b9d1e47
Revises: b91d8a143dde
Create Date: 2025-12-22 01:27:05.532944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e64b9d1e47'
down_revision = 'b91d8a143dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penalties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('penalty_type', sa.String(length=50), nullable=False),
    sa.Column('applied_by', sa.Integer(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['applied_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('blocked_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('blocked_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('payment_due_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('payment_due_date')
        batch_op.drop_column('blocked_reason')
        batch_op.drop_column('blocked_at')
        batch_op.drop_column('is_blocked')

    op.drop_table('penalties')
    # ### end Alembic commands ###
