"""Add faculties and update relationships

Revision ID: b06f57f03311
Revises: f754ff1458d2
Create Date: 2025-12-19 21:51:16.532997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b06f57f03311'
down_revision = 'f754ff1458d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faculty_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('course_id'))
        batch_op.create_foreign_key(None, 'faculties', ['faculty_id'], ['id'])

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index('idx_enrollment_course', ['course_id'], unique=False)
        batch_op.create_index('idx_enrollment_student', ['student_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faculty_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'faculties', ['faculty_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('faculty_id')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index('idx_enrollment_student')
        batch_op.drop_index('idx_enrollment_course')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('course_id'), ['course_id'], unique=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('faculty_id')

    op.drop_table('faculties')
    # ### end Alembic commands ###
