"""Add GeneratedReport model

Revision ID: b91d8a143dde
Revises: f8d12c6c8a32
Create Date: 2025-12-22 00:40:46.468138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b91d8a143dde'
down_revision = 'f8d12c6c8a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_reports',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('file_path_pdf', sa.String(length=255), nullable=True),
    sa.Column('file_path_excel', sa.String(length=255), nullable=True),
    sa.Column('file_size_pdf', sa.Integer(), nullable=True),
    sa.Column('file_size_excel', sa.Integer(), nullable=True),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated_reports')
    # ### end Alembic commands ###
